### ISSUE TITLE
Add support for short partner product name

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/quickstart-documentation-base-common#30]
Sometimes a partner product name may contain acronym which needs to be expanded only once and for rest of the occurrences, the acronym can be used. For example:

- Full product name: Citrix Web App Firewall (WAF)
- Short product name: Citrix WAF

To support this, I suggest adding a new `partner-product-name-short` key and use this in place of `partner-product-name` everywhere else except for the title.

Both  `partner-product-name-short` and `partner-product-name` keys should have the same value when there is no acronym in the product name.

**Comment by andrew-glenn** [comment]
Addressed via #41
