### ISSUE TITLE
Change "aggregate" to "finalize"

### ISSUE THREAD

**Issue by MarciaRieferJohnston** [aws-quickstart/quickstart-documentation-base-common#58]
Please change the term _aggregate_ throughout. Per Daniel's feedback: "Use our standardized language: “_finalizes_, not _aggregates_ (I know Acrolinx flags this, but don’t change it)."

**Comment by andrew-glenn** [comment]
Pull requests are welcome.

**Comment by MarciaRieferJohnston** [comment]
I'm closing this issue without requesting the edit after all. Daniel now says he prefers to stick with _aggregates_ after all.
